"""Add completed workout model

Revision ID: 5865b94e441e
Revises: 
Create Date: 2024-06-19 17:54:50.669577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5865b94e441e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_workouts_users')
    with op.batch_alter_table('completed_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_sets', sa.Integer(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout', ['workout_id'], ['id'])
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.NUMERIC(precision=2), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('total_sets')
        batch_op.drop_column('workout_id')

    op.create_table('completed_workouts_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('completed_workout_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['completed_workout_id'], ['completed_workout.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
